### PR TITLE
Pictures + updates to intro

### PR DESCRIPTION
**Pull request by story645**
-- Added another concept to the visualization section(jittering) so let me know if you want me to write that section of the markdown
-- Should I just add fig.savefig into the notebooks so that every time I change a viz, the image for the markdown gets changed too?
-- I put the visualization of the decision boundary in the middle, but let me know if I should bounce that down 'cause it'll mess with your rhythm
-- updated objective and key terms some but will again when I finish my  lesson
-- shoved the testing stuff into a notebook for now, but plan is to turn that into a gitbook section and then pull it out of the repo

### CODE REVIEW

**Comment by rachelrakov** [comment]
Hi @story645!
Answering questions from above here - let me know if my answers make sense.

-- Yes, please write that part of the visualization section (including jittering and the visualizations above it)  in the intro_to_ml_with_python notebook into it's own markdown file - you can make a markdown file that just contains everything after "Let's visualize the data!" If you can do that, I will update the markdown file where I had those visualizations before and remove the visualizations from them since they will be covered in yours.  Will you also present this part of the presentation during the workshop?

-- I guess you should add fig.savfig into the notebooks, if that means the image for the markdowns will get changed too?  I'm not sure how this works since I'm not automatically regenerating my markdown files as things get changed, I've been having to edit them on my own,  but your way sounds better.

-- Yeah, if you could move the decision boundary thing down, that would be great.  I would rather get through all of the sklearn methods together as a unit, and then have you talk about visualizing them.  That would be great, thank you!

-- I love the visualizations you have below, about taking only the separable parts of the data out and using those as features (at least I think that's what you're doing?) - a bit more explanation here would be good, especially for the gitbook.  I don't think that anyone will be able to code along with you code for making the visualizations, so for that reason it might be good for them to just download this notebook 

-- Are you worried about time?  I'm a little worried about time, if you're doing all of these visualizations and explaining them, and are also still thinking that you're going to discuss unsupervised machine learning.  I worry that there won't be enough time to get to unsupervised machine learning, and if it would be better to take time really going through these visualizations, since they help so much to visualize supervised classification.

-- I fixed a typo in the intro_to_ml_with_python notebook, repushed it to my repo, so you might want to pull it again before you work on it more.

-- Let me know when you make the final changes to the objectives and key terms, so I can add them to the existing markdown file for that section, and also when you make the "Let's visualize this data!" markdown file, so I can remove it from my features file.

-- I'm out of town sans internet starting tomorrow so I won't be able to make more changes this weekend, but I will make them when I am back at school on Tuesday.

Thanks for all of your hard work!

**Comment by story645** [comment]
>Will you also present this part of the presentation during the workshop?

Yup

> I'm not sure how this works since I'm not automatically regenerating my markdown files as things get changed, I've been having to edit them on my own, but your way sounds better.

Because the markdown points to the location of the image, I'm basically just overwriting the file it's already pointing to using the savefig.

>I love the visualizations you have below, about taking only the separable parts of the data out and using those as features (at least I think that's what you're doing?) 

Not sure which viz you're talking about here. the only viz where the data is separable is the one where I generated fake data to test that I was doing the math and viz correctly. And yes will definitely explain that more and the plan is to not talk about it during the presentation but to handwave towards it. 

> Are you worried about time? I'm a little worried about time, if you're doing all of these visualizations and explaining them, and are also still thinking that you're going to discuss unsupervised machine learning.

A little, but I also don't really plan on going through how to make the visualization and instead am thinking more about just using it as an explanation for how the algorithm works. Which actually, what if I move all the code for making the images down to the bottom, but leave the images themselves in the parts of the notebook where they can maybe help you explain what's going on?

**Comment by rachelrakov** [comment]
On Thu, May 24, 2018 at 4:11 PM, hannah <notifications@github.com> wrote:

> Will you also present this part of the presentation during the workshop?
>
> Yup
>
> I'm not sure how this works since I'm not automatically regenerating my
> markdown files as things get changed, I've been having to edit them on my
> own, but your way sounds better.
>
> Because the markdown points to the location of the image, I'm basically
> just overwriting the file it's already pointing to using the savefig.
>
So long as it won't interfere with the few images I have, then that seems
like a good idea.

> I love the visualizations you have below, about taking only the separable
> parts of the data out and using those as features (at least I think that's
> what you're doing?)
>
> Not sure which viz you're talking about here. the only viz where the data
> is separable is the one where I generated fake data to test that I was
> doing the math and viz correctly. And yes will definitely explain that more
> and the plan is to not talk about it during the presentation but to
> handwave towards it.
>
> Are you worried about time? I'm a little worried about time, if you're
> doing all of these visualizations and explaining them, and are also still
> thinking that you're going to discuss unsupervised machine learning.
>
> A little, but I also don't really plan on going through how to make the
> visualization and instead am thinking more about just using it as an
> explanation for how the algorithm works. Which actually, what if I move all
> the code for making the images down to the bottom, but leave the images
> themselves in the parts of the notebook where they can maybe help you
> explain what's going on?
>
I'm not sure about that one - I worry about explaining visualizations,
since I don't know as much about them as you do.  I think that moving the
images down for the classification stuff is a good idea, so we can have
images all together and you can explain them to the participants.

**Comment by story645** [comment]
>I'm not sure about that one - I worry about explaining visualizations, since I don't know as much about them as you do.

Can we talk about this Tuesday? The reason I want to intersperse the images is because `.fit` is about finding the decision boundary, and `.predict` is about deciding on which side of the decision boundary a point lies, and that's about all I think you need to say about the visualizations when talking through the code but I think it also concertizes what the algorithm is doing. I worry that dropping the discussion to the end may lead to a lot of redundant explanation. 

At this point I'm thinking I may just take the code out completely and shove it in an addendum 'cause I don't know that it's super salient for this lesson.

**Pull request merged**
